name: Test

on:
  push:
    branches: [main]
    paths-ignore:
      - .gitignore
      - README.md

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Clang
        uses: egor-tensin/setup-clang@v2
        with:
          version: 22
      - name: Download doctest
        run: |
          mkdir external
          wget -O external/doctest.h \
            https://github.com/doctest/doctest/releases/download/v2.4.12/doctest.h
      - name: Run tests
        run: ./.tests/run.sh
